In [59]:
import torch

In [60]:
torch.random.manual_seed(42);

In [61]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [62]:
a[0]

tensor(1.)

In [63]:
float(a[0])

1.0

In [64]:
a[1] = 3.0
a

tensor([1., 3., 1.])

In [65]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 2.0
points[2] = 7.0
points[3] = 3.0
points[4] = 4.0
points[5] = 9.0
points

tensor([4., 2., 7., 3., 4., 9.])

In [66]:
points = torch.Tensor([4.0, 2.0, 7.0, 3.0, 4.0, 9.0])
points, points.shape

(tensor([4., 2., 7., 3., 4., 9.]), torch.Size([6]))

In [67]:
points = torch.tensor([[4.0, 2.0], [7.0, 3.0], [4.0, 9.0]])
points, points.shape

(tensor([[4., 2.],
         [7., 3.],
         [4., 9.]]),
 torch.Size([3, 2]))

In [68]:
points[0], points[0, 1]

(tensor([4., 2.]), tensor(2.))

In [69]:
img_t = torch.randn(3, 5, 5) #shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7512, 0.0722])

In [70]:
batch_t = torch.randn(2, 3, 5, 5) #shape [batch, channels, rows, columns]
batch_t.shape

torch.Size([2, 3, 5, 5])

In [71]:
weights_named = torch.tensor([0.2126, 0.7512, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7512, 0.0722], names=('channels',))

In [72]:
l = [1.0, 2.0 ,3.0]
t1 = torch.tensor(l, dtype=torch.float)
t2 = torch.tensor(l, dtype=torch.float32)
t3 = torch.tensor(l, dtype=torch.int)

In [73]:
t1.dtype, t3.dtype

(torch.float32, torch.int32)

In [74]:
t1.to(torch.double)

tensor([1., 2., 3.], dtype=torch.float64)

In [75]:
points = torch.Tensor([[1, 2], [3, 4], [5, 6]])
points.storage()

 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [76]:
second_point = points[1]
second_point.storage_offset()

2

In [77]:
second_point.size()

torch.Size([2])

In [78]:
second_point.stride()

(1,)

In [79]:
points.stride()

(2, 1)

In [80]:
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [81]:
second_point = points[1]
second_point[0] = 32
points

tensor([[ 1.,  2.],
        [32.,  4.],
        [ 5.,  6.]])

In [82]:
points = torch.tensor([[1, 2], [3, 4], [5, 6]])
points

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [83]:
points_t = points.t()
points_t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [84]:
id(points.storage()), id(points_t.storage())

(140470048496064, 140470048493376)

In [112]:
id(points.storage().data_ptr())==id(points_t.storage().data_ptr())

True

In [111]:
id(points.data_ptr()) == id(points_t.data_ptr())

True

In [85]:
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [86]:
points_t.storage()

 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [87]:
points_t.stride()

(1, 2)

In [88]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1, 3, 5],
        [2, 4, 6]])

In [89]:
points_t_cont.stride()

(3, 1)

In [90]:
points_t_cont.storage()

 1
 3
 5
 2
 4
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [91]:
points_gpu = torch.tensor([[1, 2], [3, 4], [5, 6]], device='cuda')

In [92]:
#Alternative
points_gpu = points.to(device='cuda')

In [93]:
points_gpu = points.to(device='cuda:0')

In [94]:
points = points * 3
points_gpu = 2 * points.to(device='cuda')


In [95]:
points_gpu = points_gpu - 10

In [96]:
points_cpu = points_gpu.to(device='cpu')

In [97]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [98]:
points = torch.zeros(4, 2)
points_np = points.numpy()
points_np

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [99]:
points = torch.from_numpy(points_np)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [100]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
a.shape, a.stride(), a.storage_offset()

(torch.Size([9]), (1,), 0)

In [102]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [103]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [105]:
id(a.storage().data_ptr())==id(b.storage().data_ptr())

True

In [113]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [114]:
c.storage_offset(), c.stride()

(4, (3, 1))

In [117]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])